'use strict';

// Apps Script Web App 배포 후 /exec URL로 교체하세요.
const API_URL = 'https://script.google.com/macros/s/AKfycbz1fHALeY9NBzVtyzBclsj6BYhV6ks5qbCr6cN_ZUYNGnUrFgkzjb1p8RL16PLU5ifu/exec';

const state={token:sessionStorage.getItem('reservationToken')||'',user:null,dates:[],monthSlots:{},month:new Date(new Date().getFullYear(),new Date().getMonth(),1),selectedDate:'',masterSection:'users',departments:[]};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];

async function api(action,data={}){
  if(API_URL.startsWith('YOUR_')) throw new Error('app.js의 API_URL을 Apps Script Web App 주소로 설정해 주세요.');
  const response=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,token:state.token,...data})});
  const result=await response.json();
  if(!result.success) throw new Error(result.message||'요청을 처리하지 못했습니다.');
  return result.data;
}
function toast(message,error=false){const el=$('#toast');el.textContent=message;el.className=`toast show${error?' error':''}`;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.className='toast',3200)}
function busy(on){document.body.classList.toggle('loading',on)}
function fmtDate(v){return new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'long',day:'numeric',weekday:'short'}).format(new Date(`${v}T00:00:00`))}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}

async function login(company,name){busy(true);try{const data=await api('login',{company,name});state.token=data.token;state.user=data.user;sessionStorage.setItem('reservationToken',state.token);showApp();await loadDates()}catch(e){toast(e.message,true)}finally{busy(false)}}
function logout(){sessionStorage.removeItem('reservationToken');Object.assign(state,{token:'',user:null,dates:[],monthSlots:{},selectedDate:''});$('#appView').classList.add('hidden');$('#loginView').classList.remove('hidden');$('#company').value='';$('#loginName').value=''}
function showApp(){const u=state.user;$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');$('#userName').textContent=u.name;$('#userDepartment').textContent=[u.company,u.departmentName].filter(Boolean).join(' · ');$('#masterTab').classList.toggle('hidden',!u.isMaster);$('#adminModeBtn').classList.toggle('hidden',!!u.isMaster)}
async function enableAdminMode(){const adminCode=prompt('관리자 코드를 입력해 주세요.');if(adminCode===null)return;busy(true);try{const data=await api('enableAdminMode',{adminCode});state.token=data.token;state.user=data.user;sessionStorage.setItem('reservationToken',state.token);showApp();toast('관리자 모드가 활성화되었습니다.')}catch(e){toast(e.message,true)}finally{busy(false)}}
async function restore(){if(!state.token)return;try{const data=await api('getSession');state.user=data.user;showApp();await loadDates()}catch{logout()}}

async function loadDates(){const slots=await api('getCalendarAll');state.monthSlots=slots.reduce((groups,slot)=>{(groups[slot.date]??=[]).push(slot);return groups},{});state.dates=Object.keys(state.monthSlots);renderCalendar()}
function ymd(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function locationClass(location){if(location.includes('티에스이 3'))return'location-tse3';if(location.includes('티에스이 2'))return'location-tse2';if(location.includes('메가센'))return'location-megasen';if(location.includes('메가터치'))return'location-megatouch';if(location.includes('타이거일렉'))return'location-tiger';if(location.includes('지엠테스트'))return'location-gm';if(location.includes('엘디티'))return'location-ldt';return'location-default'}
function renderCalendar(){const months=[...new Set(state.dates.map(d=>d.slice(0,7)))];$('#calendar').innerHTML=months.map(monthKey=>{const [y,m1]=monthKey.split('-').map(Number),m=m1-1,first=new Date(y,m,1),last=new Date(y,m+1,0),start=new Date(y,m,1-first.getDay()),weeks=Math.ceil((first.getDay()+last.getDate())/7),cells=weeks*7;let days='';for(let i=0;i<cells;i++){const d=new Date(start);d.setDate(start.getDate()+i);const key=ymd(d),inside=d.getMonth()===m,slots=inside?(state.monthSlots[key]||[]):[],location=slots[0]?.location||'',slotHtml=slots.map(s=>`<button type="button" class="calendar-slot ${s.available?'available':'booked'}" aria-label="${esc(s.startTime)}부터 ${esc(s.endTime)}까지 ${s.available?'예약 가능':'예약 마감'}" ${s.available?`data-reserve="${esc(s.slotId)}"`:'disabled'}><span class="slot-time"><span>${esc(s.startTime)}</span><span class="slot-end">–${esc(s.endTime)}</span></span><small>${s.available?'예약':'마감'}</small></button>`).join('');days+=`<div class="day ${inside?'in-month':''} ${key===ymd(new Date())?'today':''}"><div class="day-heading ${location?locationClass(location):''}"><strong class="day-number">${d.getDate()}</strong>${location?`<span class="day-location">${esc(location)}</span>`:''}</div><div class="day-slots">${slotHtml}</div></div>`}return`<section class="calendar-month"><h3>${y}년 ${m1}월</h3><div class="weekdays"><span>일</span><span>월</span><span>화</span><span>수</span><span>목</span><span>금</span><span>토</span></div><div class="calendar-grid">${days}</div></section>`}).join('')||'<div class="empty-state">등록된 예약 일정이 없습니다.</div>'}
async function reserve(slotId){if(!confirm('선택한 시간으로 예약하시겠습니까?'))return;busy(true);try{const reservations=await api('getMyReservations');if(reservations.some(r=>r.status==='ACTIVE'))throw new Error('예약은 1인당 1개만 가능합니다. 기존 예약을 취소한 후 다시 예약해 주세요.');await api('createReservation',{slotId});toast('예약이 완료되었습니다.');await loadDates()}catch(e){toast(e.message,true)}finally{busy(false)}}
async function loadMy(){const rows=await api('getMyReservations');$('#myReservations').innerHTML=table(['예약 날짜','예약 시간','상태','관리'],rows.map(r=>[fmtDate(r.date),`${r.startTime} – ${r.endTime}`,badge(r.status),r.status==='ACTIVE'?`<button type="button" class="btn danger" data-cancel="${esc(r.reservationId)}">예약 취소</button>`:'-']))}
async function cancelMine(id){if(!confirm('예약을 취소하시겠습니까?'))return;try{await api('cancelReservation',{reservationId:id});toast('예약이 취소되었습니다.');await loadMy();await loadDates()}catch(e){toast(e.message,true)}}
function badge(status){return `<span class="badge ${status==='ACTIVE'?'active':'cancelled'}">${status==='ACTIVE'?'예약':'취소'}</span>`}
function table(headers,rows){return `<table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${headers.length}">조회된 데이터가 없습니다.</td></tr>`}</tbody></table>`}

async function loadMaster(){if(!state.user?.isMaster)return;busy(true);try{state.departments=await api('getDepartments');if(state.masterSection==='users')await masterUsers();if(state.masterSection==='departments')masterDepartments(state.departments);if(state.masterSection==='availability')await masterAvailability();if(state.masterSection==='reservations')await masterReservations()}catch(e){toast(e.message,true)}finally{busy(false)}}
async function masterUsers(){const rows=await api('getUsers');$('#masterContent').innerHTML=`<article class="card"><div class="section-head"><div><h2>사용자 관리</h2><p>회사명, 부서, 이름과 사용 여부를 관리합니다.</p></div><button class="btn primary" data-add-user>사용자 추가</button></div><div class="table-wrap">${table(['회사명','부서','이름','사용','관리'],rows.map(r=>[esc(r.company),esc(r.departmentName),esc(r.name),r.enabled?'사용':'중지',`<button class="btn secondary" data-edit-user='${encodeURIComponent(JSON.stringify(r))}'>수정</button>`]))}</div></article>`}
function masterDepartments(rows){$('#masterContent').innerHTML=`<article class="card"><div class="section-head"><div><h2>부서 관리</h2><p>회사별 부서를 관리합니다.</p></div><button class="btn primary" data-add-dept>부서 추가</button></div><div class="table-wrap">${table(['회사명','부서명','사용','관리'],rows.map(r=>[esc(r.company),esc(r.departmentName),r.enabled?'사용':'중지',`<button class="btn secondary" data-edit-dept='${encodeURIComponent(JSON.stringify(r))}'>수정</button>`]))}</div></article>`}
async function masterAvailability(){const from=ymd(new Date()),untilDate=new Date();untilDate.setMonth(untilDate.getMonth()+6);const to=ymd(untilDate);const rows=await api('getAvailability',{from,to});$('#masterContent').innerHTML=`<article class="card"><div class="section-head"><div><h2>예약 일정 관리</h2><p>전체 사용자가 이용할 날짜와 시간을 등록합니다.</p></div><button class="btn primary" data-add-slot>일정 추가</button></div><div class="table-wrap">${table(['날짜','시간','장소','사용','관리'],rows.map(r=>[esc(r.date),`${esc(r.startTime)} – ${esc(r.endTime)}`,esc(r.location||''),r.enabled?'사용':'중지',`<button class="btn secondary" data-edit-slot='${encodeURIComponent(JSON.stringify(r))}'>수정</button>`]))}</div></article>`}
async function masterReservations(){const rows=await api('getAllReservations',{});state.masterReservations=rows;$('#masterContent').innerHTML=`<article class="card"><div class="section-head"><div><h2>전체 예약 현황</h2><p>전체 회사의 예약과 취소 이력을 조회합니다.</p></div><button type="button" class="btn primary" data-export-reservations>최종 예약 리스트 다운로드</button></div><div class="table-wrap">${table(['날짜','시간','장소','회사명','부서','이름','상태','관리'],rows.map(r=>[esc(r.date),`${r.startTime} – ${r.endTime}`,esc(r.location||''),esc(r.company),esc(r.departmentName),esc(r.name),badge(r.status),r.status==='ACTIVE'?`<button class="btn danger" data-master-cancel="${esc(r.reservationId)}">취소</button>`:'-']))}</div></article>`}
function exportActiveReservations(){const rows=(state.masterReservations||[]).filter(r=>r.status==='ACTIVE');if(!rows.length){toast('다운로드할 최종 예약이 없습니다.',true);return}const csvRows=[['예약 날짜','시작 시간','종료 시간','장소','회사명','부서','이름'],...rows.map(r=>[r.date,r.startTime,r.endTime,r.location||'',r.company,r.departmentName,r.name])],quote=v=>{let s=String(v??'');if(/^[=+\-@\t\r]/.test(s))s=`'${s}`;return`"${s.replace(/"/g,'""')}"`},csv='\uFEFF'+csvRows.map(row=>row.map(quote).join(',')).join('\r\n'),url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=`최종_예약_리스트_${ymd(new Date())}.csv`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);toast(`최종 예약 ${rows.length}건을 다운로드했습니다.`)}

function openForm(type,item={}){const d=$('#formDialog'),f=$('#dialogForm');f.dataset.type=type;f.dataset.original=JSON.stringify(item);const depOpts=state.departments.filter(x=>x.enabled||x.departmentId===item.departmentId).map(x=>`<option value="${esc(x.departmentId)}" ${x.departmentId===item.departmentId?'selected':''}>${esc(x.company)} · ${esc(x.departmentName)}</option>`).join('');const field=(n,l,t='text',v='',wide='')=>`<div class="${wide}"><label>${l}</label><input name="${n}" type="${t}" value="${esc(v)}" required></div>`;if(type==='user'){ $('#dialogTitle').textContent=item.userId?'사용자 수정':'사용자 추가';$('#dialogFields').innerHTML=field('company','회사명','text',item.company||'')+field('name','이름','text',item.name||'')+`<div><label>부서</label><select name="departmentId" required>${depOpts}</select></div><div><label>사용 여부</label><select name="enabled"><option value="true" ${item.enabled!==false?'selected':''}>사용</option><option value="false" ${item.enabled===false?'selected':''}>중지</option></select></div>`}if(type==='department'){ $('#dialogTitle').textContent=item.departmentId?'부서 수정':'부서 추가';$('#dialogFields').innerHTML=field('company','회사명','text',item.company||'')+field('departmentName','부서명','text',item.departmentName||'')+`<div><label>사용 여부</label><select name="enabled"><option value="true" ${item.enabled!==false?'selected':''}>사용</option><option value="false" ${item.enabled===false?'selected':''}>중지</option></select></div>`}if(type==='slot'){ $('#dialogTitle').textContent=item.slotId?'예약 일정 수정':'예약 일정 추가';$('#dialogFields').innerHTML=field('date','날짜','date',item.date||ymd(new Date()))+field('startTime','시작 시간','time',item.startTime||'09:00')+field('endTime','종료 시간','time',item.endTime||'10:00')+`<div><label>장소</label><input name="location" type="text" value="${esc(item.location||'')}"></div><div><label>사용 여부</label><select name="enabled"><option value="true" ${item.enabled!==false?'selected':''}>사용</option><option value="false" ${item.enabled===false?'selected':''}>중지</option></select></div>`}d.showModal()}
async function saveDialog(){const f=$('#dialogForm'),type=f.dataset.type,fd=Object.fromEntries(new FormData(f));fd.enabled=fd.enabled==='true';const original=JSON.parse(f.dataset.original||'{}');try{if(type==='user')await api('saveUser',{user:{...original,...fd}});if(type==='department')await api('saveDepartment',{department:{...original,...fd}});if(type==='slot')await api('saveAvailability',{availability:{...original,...fd}});$('#formDialog').close();toast('저장되었습니다.');await loadMaster()}catch(e){toast(e.message,true)}}

document.addEventListener('click',async e=>{const t=e.target.closest('button');if(!t)return;if(t.dataset.view){$$('.tab').forEach(x=>x.classList.toggle('active',x===t));$$('.panel-view').forEach(x=>x.classList.add('hidden'));$(`#${t.dataset.view}Panel`).classList.remove('hidden');if(t.dataset.view==='my')await loadMy();if(t.dataset.view==='master')await loadMaster()}if(t.dataset.reserve)reserve(t.dataset.reserve);if(t.dataset.cancel)cancelMine(t.dataset.cancel);if(t.dataset.master){$$('.subtab').forEach(x=>x.classList.toggle('active',x===t));state.masterSection=t.dataset.master;loadMaster()}if(t.matches('[data-export-reservations]'))exportActiveReservations();if(t.matches('[data-add-user]'))openForm('user');if(t.dataset.editUser)openForm('user',JSON.parse(decodeURIComponent(t.dataset.editUser)));if(t.matches('[data-add-dept]'))openForm('department');if(t.dataset.editDept)openForm('department',JSON.parse(decodeURIComponent(t.dataset.editDept)));if(t.matches('[data-add-slot]'))openForm('slot');if(t.dataset.editSlot)openForm('slot',JSON.parse(decodeURIComponent(t.dataset.editSlot)));if(t.dataset.masterCancel&&confirm('해당 예약을 취소하시겠습니까?')){try{await api('cancelReservationByMaster',{reservationId:t.dataset.masterCancel});toast('예약을 취소했습니다.');loadMaster()}catch(err){toast(err.message,true)}}});
$('#loginForm').addEventListener('submit',e=>{e.preventDefault();login($('#company').value.trim(),$('#loginName').value.trim())});$('#adminModeBtn').onclick=enableAdminMode;$('#logoutBtn').onclick=logout;$('#refreshMyBtn').onclick=loadMy;$('#dialogClose').onclick=$('#dialogCancel').onclick=()=>$('#formDialog').close();$('#dialogForm').addEventListener('submit',e=>{e.preventDefault();saveDialog()});restore();
