'use strict';

// Apps Script Web App 배포 후 /exec URL로 교체하세요.
const API_URL = 'https://script.google.com/macros/s/AKfycbz1fHALeY9NBzVtyzBclsj6BYhV6ks5qbCr6cN_ZUYNGnUrFgkzjb1p8RL16PLU5ifu/exec';

const state={token:sessionStorage.getItem('reservationToken')||'',user:null,dates:[],month:new Date(new Date().getFullYear(),new Date().getMonth(),1),selectedDate:'',masterSection:'users',departments:[]};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];

async function api(action,data={}){
  if(API_URL.startsWith('YOUR_')) throw new Error('app.js의 API_URL을 Apps Script Web App 주소로 설정해 주세요.');
  const response=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,token:state.token,...data})});
  const result=await response.json();
  if(!result.success) throw new Error(result.message||'요청을 처리하지 못했습니다.');
  return result.data;
}
function toast(message,error=false){const el=$('#toast');el.textContent=message;el.className=`toast show${error?' error':''}`;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.className='toast',3200)}
function busy(on){document.body.classList.toggle('loading',on)}
function fmtDate(v){return new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'long',day:'numeric',weekday:'short'}).format(new Date(`${v}T00:00:00`))}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}

async function login(employeeId){busy(true);try{const data=await api('login',{employeeId});state.token=data.token;state.user=data.user;sessionStorage.setItem('reservationToken',state.token);showApp();await loadDates()}catch(e){toast(e.message,true)}finally{busy(false)}}
function logout(){sessionStorage.removeItem('reservationToken');Object.assign(state,{token:'',user:null,dates:[],selectedDate:''});$('#appView').classList.add('hidden');$('#loginView').classList.remove('hidden');$('#employeeId').value=''}
function showApp(){const u=state.user;$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');$('#userName').textContent=u.name;$('#userDepartment').textContent=u.departmentName||u.departmentId;$('#masterTab').classList.toggle('hidden',!u.isMaster)}
async function restore(){if(!state.token)return;try{const data=await api('getSession');state.user=data.user;showApp();await loadDates()}catch{logout()}}

async function loadDates(){const y=state.month.getFullYear(),m=state.month.getMonth()+1;state.dates=await api('getAvailableDates',{year:y,month:m});renderCalendar()}
function ymd(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function renderCalendar(){const y=state.month.getFullYear(),m=state.month.getMonth();$('#monthTitle').textContent=`${y}년 ${m+1}월`;const first=new Date(y,m,1),start=new Date(y,m,1-first.getDay()),available=new Set(state.dates);let html='';for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const key=ymd(d),inside=d.getMonth()===m,isAvail=available.has(key);html+=`<button class="day ${inside?'in-month':''} ${isAvail?'available':''} ${key===state.selectedDate?'selected':''} ${key===ymd(new Date())?'today':''}" ${isAvail?`data-date="${key}"`:'disabled'}>${d.getDate()}</button>`}$('#calendar').innerHTML=html}
async function selectDate(date){state.selectedDate=date;renderCalendar();$('#selectedDateLabel').textContent=fmtDate(date);$('#slotList').innerHTML='<div class="empty-state">시간을 불러오는 중입니다.</div>';try{const slots=await api('getAvailableSlots',{date});renderSlots(slots)}catch(e){toast(e.message,true)}}
function renderSlots(slots){if(!slots.length){$('#slotList').innerHTML='<div class="empty-state">예약 가능한 시간이 없습니다.</div>';return}$('#slotList').innerHTML=slots.map(s=>`<div class="slot-row ${s.available?'':'booked'}"><div><strong>${esc(s.startTime)} – ${esc(s.endTime)}</strong><small>${s.available?'예약 가능':'예약 완료'}</small></div><button class="btn ${s.available?'primary':'ghost'}" ${s.available?`data-reserve="${esc(s.slotId)}"`:'disabled'}>${s.available?'예약':'마감'}</button></div>`).join('')}
async function reserve(slotId){if(!confirm('선택한 시간으로 예약하시겠습니까?'))return;busy(true);try{const reservations=await api('getMyReservations');if(reservations.some(r=>r.status==='ACTIVE'))throw new Error('예약은 1인당 1개만 가능합니다. 기존 예약을 취소한 후 다시 예약해 주세요.');await api('createReservation',{slotId});toast('예약이 완료되었습니다.');await selectDate(state.selectedDate)}catch(e){toast(e.message,true)}finally{busy(false)}}
async function loadMy(){const rows=await api('getMyReservations');$('#myReservations').innerHTML=table(['예약 날짜','예약 시간','상태','관리'],rows.map(r=>[fmtDate(r.date),`${r.startTime} – ${r.endTime}`,badge(r.status),r.status==='ACTIVE'?`<button type="button" class="btn danger" data-cancel="${esc(r.reservationId)}">예약 취소</button>`:'-']))}
async function cancelMine(id){if(!confirm('예약을 취소하시겠습니까?'))return;try{await api('cancelReservation',{reservationId:id});toast('예약이 취소되었습니다.');await loadMy();await loadDates()}catch(e){toast(e.message,true)}}
function badge(status){return `<span class="badge ${status==='ACTIVE'?'active':'cancelled'}">${status==='ACTIVE'?'예약':'취소'}</span>`}
function table(headers,rows){return `<table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${headers.length}">조회된 데이터가 없습니다.</td></tr>`}</tbody></table>`}

async function loadMaster(){if(!state.user?.isMaster)return;busy(true);try{state.departments=await api('getDepartments');if(state.masterSection==='users')await masterUsers();if(state.masterSection==='departments')masterDepartments(state.departments);if(state.masterSection==='availability')await masterAvailability();if(state.masterSection==='reservations')await masterReservations()}catch(e){toast(e.message,true)}finally{busy(false)}}
async function masterUsers(){const rows=await api('getUsers');$('#masterContent').innerHTML=`<article class="card"><div class="section-head"><div><h2>사용자 관리</h2><p>사번, 이름, 사업부와 사용 여부를 관리합니다.</p></div><button class="btn primary" data-add-user>사용자 추가</button></div><div class="table-wrap">${table(['사번','이름','사업부','사용','관리'],rows.map(r=>[esc(r.employeeId),esc(r.name),esc(r.departmentName||r.departmentId),r.enabled?'사용':'중지',`<button class="btn secondary" data-edit-user='${encodeURIComponent(JSON.stringify(r))}'>수정</button>`]))}</div></article>`}
function masterDepartments(rows){$('#masterContent').innerHTML=`<article class="card"><div class="section-head"><div><h2>사업부 관리</h2><p>예약 대상을 구분하는 사업부를 관리합니다.</p></div><button class="btn primary" data-add-dept>사업부 추가</button></div><div class="table-wrap">${table(['사업부 ID','사업부명','사용','관리'],rows.map(r=>[esc(r.departmentId),esc(r.departmentName),r.enabled?'사용':'중지',`<button class="btn secondary" data-edit-dept='${encodeURIComponent(JSON.stringify(r))}'>수정</button>`]))}</div></article>`}
async function masterAvailability(){const from=ymd(new Date()),untilDate=new Date();untilDate.setMonth(untilDate.getMonth()+3);const to=ymd(untilDate);const rows=await api('getAvailability',{from,to});$('#masterContent').innerHTML=`<article class="card"><div class="section-head"><div><h2>예약 일정 관리</h2><p>사업부별 날짜와 시간 범위를 등록합니다.</p></div><button class="btn primary" data-add-slot>일정 추가</button></div><div class="table-wrap">${table(['날짜','시간','사업부','사용','관리'],rows.map(r=>[esc(r.date),`${esc(r.startTime)} – ${esc(r.endTime)}`,esc(r.departmentName||r.departmentId),r.enabled?'사용':'중지',`<button class="btn secondary" data-edit-slot='${encodeURIComponent(JSON.stringify(r))}'>수정</button>`]))}</div></article>`}
async function masterReservations(){const rows=await api('getAllReservations',{});$('#masterContent').innerHTML=`<article class="card"><div class="section-head"><div><h2>전체 예약 현황</h2><p>전체 사업부의 예약과 취소 이력을 조회합니다.</p></div></div><div class="table-wrap">${table(['날짜','시간','사번','이름','사업부','상태','관리'],rows.map(r=>[esc(r.date),`${r.startTime} – ${r.endTime}`,esc(r.employeeId),esc(r.name),esc(r.departmentName||r.departmentId),badge(r.status),r.status==='ACTIVE'?`<button class="btn danger" data-master-cancel="${esc(r.reservationId)}">취소</button>`:'-']))}</div></article>`}

function openForm(type,item={}){const d=$('#formDialog'),f=$('#dialogForm');f.dataset.type=type;f.dataset.original=JSON.stringify(item);const depOpts=state.departments.filter(x=>x.enabled||x.departmentId===item.departmentId).map(x=>`<option value="${esc(x.departmentId)}" ${x.departmentId===item.departmentId?'selected':''}>${esc(x.departmentName)}</option>`).join('');const field=(n,l,t='text',v='',wide='',attrs='')=>`<div class="${wide}"><label>${l}</label><input name="${n}" type="${t}" value="${esc(v)}" ${attrs} required></div>`;if(type==='user'){ $('#dialogTitle').textContent=item.employeeId?'사용자 수정':'사용자 추가';$('#dialogFields').innerHTML=field('employeeId','사번','text',item.employeeId||'','','inputmode="numeric" minlength="8" maxlength="8" pattern="\\d{8}" title="8자리 숫자를 입력해 주세요."')+field('name','이름','text',item.name||'')+`<div><label>사업부</label><select name="departmentId" required>${depOpts}</select></div><div><label>사용 여부</label><select name="enabled"><option value="true" ${item.enabled!==false?'selected':''}>사용</option><option value="false" ${item.enabled===false?'selected':''}>중지</option></select></div>`}if(type==='department'){ $('#dialogTitle').textContent=item.departmentId?'사업부 수정':'사업부 추가';$('#dialogFields').innerHTML=field('departmentId','사업부 ID','text',item.departmentId||'')+field('departmentName','사업부명','text',item.departmentName||'')+`<div><label>사용 여부</label><select name="enabled"><option value="true" ${item.enabled!==false?'selected':''}>사용</option><option value="false" ${item.enabled===false?'selected':''}>중지</option></select></div>`}if(type==='slot'){ $('#dialogTitle').textContent=item.slotId?'예약 일정 수정':'예약 일정 추가';$('#dialogFields').innerHTML=field('date','날짜','date',item.date||ymd(new Date()))+field('startTime','시작 시간','time',item.startTime||'09:00')+field('endTime','종료 시간','time',item.endTime||'10:00')+`<div><label>사업부</label><select name="departmentId" required>${depOpts}</select></div><div><label>사용 여부</label><select name="enabled"><option value="true" ${item.enabled!==false?'selected':''}>사용</option><option value="false" ${item.enabled===false?'selected':''}>중지</option></select></div>`}d.showModal()}
async function saveDialog(){const f=$('#dialogForm'),type=f.dataset.type,fd=Object.fromEntries(new FormData(f));fd.enabled=fd.enabled==='true';const original=JSON.parse(f.dataset.original||'{}');try{if(type==='user')await api('saveUser',{user:{...original,...fd}});if(type==='department')await api('saveDepartment',{department:{...original,...fd}});if(type==='slot')await api('saveAvailability',{availability:{...original,...fd}});$('#formDialog').close();toast('저장되었습니다.');await loadMaster()}catch(e){toast(e.message,true)}}

document.addEventListener('click',async e=>{const t=e.target.closest('button');if(!t)return;if(t.dataset.view){$$('.tab').forEach(x=>x.classList.toggle('active',x===t));$$('.panel-view').forEach(x=>x.classList.add('hidden'));$(`#${t.dataset.view}Panel`).classList.remove('hidden');if(t.dataset.view==='my')await loadMy();if(t.dataset.view==='master')await loadMaster()}if(t.dataset.date)selectDate(t.dataset.date);if(t.dataset.reserve)reserve(t.dataset.reserve);if(t.dataset.cancel)cancelMine(t.dataset.cancel);if(t.dataset.master){$$('.subtab').forEach(x=>x.classList.toggle('active',x===t));state.masterSection=t.dataset.master;loadMaster()}if(t.matches('[data-add-user]'))openForm('user');if(t.dataset.editUser)openForm('user',JSON.parse(decodeURIComponent(t.dataset.editUser)));if(t.matches('[data-add-dept]'))openForm('department');if(t.dataset.editDept)openForm('department',JSON.parse(decodeURIComponent(t.dataset.editDept)));if(t.matches('[data-add-slot]'))openForm('slot');if(t.dataset.editSlot)openForm('slot',JSON.parse(decodeURIComponent(t.dataset.editSlot)));if(t.dataset.masterCancel&&confirm('해당 예약을 취소하시겠습니까?')){try{await api('cancelReservationByMaster',{reservationId:t.dataset.masterCancel});toast('예약을 취소했습니다.');loadMaster()}catch(err){toast(err.message,true)}}});
$('#loginForm').addEventListener('submit',e=>{e.preventDefault();login($('#employeeId').value.trim())});$('#logoutBtn').onclick=logout;$('#prevMonth').onclick=()=>{state.month.setMonth(state.month.getMonth()-1);loadDates()};$('#nextMonth').onclick=()=>{state.month.setMonth(state.month.getMonth()+1);loadDates()};$('#refreshMyBtn').onclick=loadMy;$('#dialogClose').onclick=$('#dialogCancel').onclick=()=>$('#formDialog').close();$('#dialogForm').addEventListener('submit',e=>{e.preventDefault();saveDialog()});restore();
