'use strict';

/** Apps Script 프로젝트 속성에 SPREADSHEET_ID 키로 실제 ID를 저장하세요. */
const CONFIG={TIME_ZONE:'Asia/Seoul',SESSION_TTL_SECONDS:21600,BLOCKED_DATES:['2026-09-01','2026-09-02','2026-09-03','2026-09-04','2026-09-07','2026-09-08','2026-09-09','2026-09-10','2026-09-11','2026-09-14','2026-09-15','2026-09-16','2026-09-22','2026-09-24','2026-09-25','2026-10-08','2026-10-09','2026-10-15','2026-11-02'],SHEETS:{USERS:'Users',DEPARTMENTS:'Departments',SLOTS:'AvailableSlots',RESERVATIONS:'Reservations',MASTERS:'Masters'}};
const HEADERS={Users:['userId','company','departmentId','name','enabled'],Departments:['departmentId','company','departmentName','enabled'],AvailableSlots:['slotId','date','startTime','endTime','enabled'],Reservations:['reservationId','date','startTime','endTime','userId','company','name','departmentId','status','createdAt'],Masters:['company','departmentName','name','enabled']};

function doGet(){return json_({success:true,data:{service:'Reservation API',status:'ok'}})}
function doPost(e){try{const req=JSON.parse((e.postData&&e.postData.contents)||'{}');if(!req.action)throw new AppError('action이 필요합니다.');const handlers={login:login_,enableAdminMode:enableAdminMode_,getSession:getSession_,getAvailableDates:getAvailableDates_,getAvailableSlots:getAvailableSlots_,getCalendarMonth:getCalendarMonth_,getCalendarAll:getCalendarAll_,createReservation:createReservation_,getMyReservations:getMyReservations_,cancelReservation:cancelReservation_,getUsers:getUsers_,saveUser:saveUser_,getDepartments:getDepartments_,saveDepartment:saveDepartment_,getAvailability:getAvailability_,saveAvailability:saveAvailability_,getAllReservations:getAllReservations_,cancelReservationByMaster:cancelReservationByMaster_};if(!handlers[req.action])throw new AppError('지원하지 않는 요청입니다.');return json_({success:true,data:handlers[req.action](req)})}catch(err){console.error(err.stack||err);return json_({success:false,message:err instanceof AppError?err.message:'서버 오류가 발생했습니다. 잠시 후 다시 시도해 주세요.'})}}
function json_(obj){return ContentService.createTextOutput(JSON.stringify(obj)).setMimeType(ContentService.MimeType.JSON)}
function AppError(message){this.name='AppError';this.message=message}AppError.prototype=Object.create(Error.prototype);

function ss_(){const id=PropertiesService.getScriptProperties().getProperty('SPREADSHEET_ID');if(!id)throw new Error('SPREADSHEET_ID가 설정되지 않았습니다.');return SpreadsheetApp.openById(id)}
function sheet_(name){const sh=ss_().getSheetByName(name);if(!sh)throw new Error(`${name} 시트가 없습니다.`);return sh}
function rows_(name){const sh=sheet_(name),last=sh.getLastRow();if(last<2)return[];const headers=HEADERS[name],values=sh.getRange(2,1,last-1,headers.length).getDisplayValues();return values.filter(r=>r.some(v=>v!=='' )).map((r,i)=>{const o={_row:i+2};headers.forEach((h,j)=>o[h]=r[j]);return o})}
function bool_(v){return v===true||String(v).toUpperCase()==='TRUE'||String(v)==='1'}
function requiredText_(v,label){v=String(v||'').trim();if(!v)throw new AppError(`${label}을(를) 입력해 주세요.`);if(v.length>100)throw new AppError(`${label}이(가) 너무 깁니다.`);return v}
function validDate_(v){v=String(v||'');if(!/^\d{4}-\d{2}-\d{2}$/.test(v)||isNaN(new Date(`${v}T00:00:00+09:00`).getTime()))throw new AppError('날짜 형식이 올바르지 않습니다.');return v}
function validTime_(v){v=String(v||'');if(!/^(?:[01]\d|2[0-3]):[0-5]\d$/.test(v))throw new AppError('시간 형식이 올바르지 않습니다.');return v}
function normalizeDate_(v){if(v instanceof Date)return Utilities.formatDate(v,CONFIG.TIME_ZONE,'yyyy-MM-dd');const s=String(v||'').trim();const m=s.match(/^(\d{4})[-\/.](\d{1,2})[-\/.](\d{1,2})$/);return m?`${m[1]}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`:s}
function normalizeTime_(v){if(v instanceof Date)return Utilities.formatDate(v,CONFIG.TIME_ZONE,'HH:mm');const s=String(v||'').trim();const m=s.match(/^(\d{1,2}):(\d{2})/);return m?`${m[1].padStart(2,'0')}:${m[2]}`:s}
function nowKey_(){return Utilities.formatDate(new Date(),CONFIG.TIME_ZONE,'yyyy-MM-dd HH:mm')}
function isPast_(date,time){return `${date} ${time}`<=nowKey_()}
function isBookableDate_(date){date=validDate_(normalizeDate_(date));const day=new Date(`${date}T00:00:00+09:00`).getDay();return day!==0&&day!==6&&!CONFIG.BLOCKED_DATES.includes(date)}
function uuid_(){return Utilities.getUuid()}

function findUser_(company,name){return rows_(CONFIG.SHEETS.USERS).find(r=>r.company===company&&r.name===name)}
function findUserById_(userId){return rows_(CONFIG.SHEETS.USERS).find(r=>r.userId===userId)}
function departmentMap_(){const map={};rows_(CONFIG.SHEETS.DEPARTMENTS).forEach(r=>map[r.departmentId]=r);return map}
function isMasterUser_(user){const dept=departmentMap_()[user.departmentId];return rows_(CONFIG.SHEETS.MASTERS).some(r=>r.company===user.company&&r.name===user.name&&r.departmentName===(dept?dept.departmentName:'')&&bool_(r.enabled))}
function createSession_(user,isMaster){const token=uuid_(),payload={userId:user.userId,isMaster:!!isMaster,nonce:uuid_()};CacheService.getScriptCache().put(`session:${token}`,JSON.stringify(payload),CONFIG.SESSION_TTL_SECONDS);return token}
function auth_(req,masterOnly){const token=String(req.token||'');if(!token)throw new AppError('로그인이 필요합니다.');const raw=CacheService.getScriptCache().get(`session:${token}`);if(!raw)throw new AppError('로그인 시간이 만료되었습니다. 다시 로그인해 주세요.');const payload=JSON.parse(raw),user=findUserById_(payload.userId);if(!user||!bool_(user.enabled))throw new AppError('사용할 수 없는 계정입니다.');const isMaster=!!payload.isMaster&&isMasterUser_(user);if(masterOnly&&!isMaster)throw new AppError('관리자 권한이 필요합니다.');CacheService.getScriptCache().put(`session:${token}`,raw,CONFIG.SESSION_TTL_SECONDS);return{user,isMaster}}
function publicUser_(user,isMaster){const dept=departmentMap_()[user.departmentId];return{userId:user.userId,company:user.company,name:user.name,departmentId:user.departmentId,departmentName:dept?dept.departmentName:'',isMaster}}

function login_(req){const company=requiredText_(req.company,'회사명'),name=requiredText_(req.name,'이름'),user=findUser_(company,name);if(!user)throw new AppError('등록되지 않은 회사명 또는 이름입니다.');if(!bool_(user.enabled))throw new AppError('사용이 중지된 계정입니다. 관리자에게 문의해 주세요.');return{token:createSession_(user,false),user:publicUser_(user,false)}}
function enableAdminMode_(req){const a=auth_(req,false),expected=PropertiesService.getScriptProperties().getProperty('ADMIN_ACCESS_CODE');if(!expected||String(req.adminCode||'')!==expected||!isMasterUser_(a.user))throw new AppError('관리자 정보 또는 코드가 올바르지 않습니다.');const token=createSession_(a.user,true);return{token,user:publicUser_(a.user,true)}}
function getSession_(req){const a=auth_(req,false);return{user:publicUser_(a.user,a.isMaster)}}
function getAvailableDates_(req){auth_(req,false);const year=Number(req.year),month=Number(req.month);if(!Number.isInteger(year)||year<2020||year>2100||!Number.isInteger(month)||month<1||month>12)throw new AppError('조회 월이 올바르지 않습니다.');const prefix=`${year}-${String(month).padStart(2,'0')}-`;const activeReservations=new Set(rows_(CONFIG.SHEETS.RESERVATIONS).filter(r=>r.status==='ACTIVE').map(r=>`${normalizeDate_(r.date)}|${normalizeTime_(r.startTime)}|${normalizeTime_(r.endTime)}`));return[...new Set(rows_(CONFIG.SHEETS.SLOTS).filter(s=>bool_(s.enabled)&&isBookableDate_(s.date)&&normalizeDate_(s.date).startsWith(prefix)&&!isPast_(normalizeDate_(s.date),normalizeTime_(s.startTime))&&!activeReservations.has(`${normalizeDate_(s.date)}|${normalizeTime_(s.startTime)}|${normalizeTime_(s.endTime)}`)).map(s=>normalizeDate_(s.date)))].sort()}
function getAvailableSlots_(req){auth_(req,false);const date=validDate_(normalizeDate_(req.date));if(!isBookableDate_(date))return[];const active=new Set(rows_(CONFIG.SHEETS.RESERVATIONS).filter(r=>r.status==='ACTIVE'&&normalizeDate_(r.date)===date).map(r=>`${normalizeTime_(r.startTime)}|${normalizeTime_(r.endTime)}`));return rows_(CONFIG.SHEETS.SLOTS).filter(s=>bool_(s.enabled)&&normalizeDate_(s.date)===date).map(s=>({slotId:s.slotId,date,startTime:normalizeTime_(s.startTime),endTime:normalizeTime_(s.endTime),available:!isPast_(date,normalizeTime_(s.startTime))&&!active.has(`${normalizeTime_(s.startTime)}|${normalizeTime_(s.endTime)}`)})).sort((x,y)=>x.startTime.localeCompare(y.startTime))}
function getCalendarMonth_(req){auth_(req,false);const year=Number(req.year),month=Number(req.month);if(!Number.isInteger(year)||year<2020||year>2100||!Number.isInteger(month)||month<1||month>12)throw new AppError('조회 월이 올바르지 않습니다.');const prefix=`${year}-${String(month).padStart(2,'0')}-`,active=new Set(rows_(CONFIG.SHEETS.RESERVATIONS).filter(r=>r.status==='ACTIVE').map(r=>`${normalizeDate_(r.date)}|${normalizeTime_(r.startTime)}|${normalizeTime_(r.endTime)}`));return rows_(CONFIG.SHEETS.SLOTS).filter(s=>bool_(s.enabled)&&isBookableDate_(s.date)&&normalizeDate_(s.date).startsWith(prefix)).map(s=>{const date=normalizeDate_(s.date),startTime=normalizeTime_(s.startTime),endTime=normalizeTime_(s.endTime);return{slotId:s.slotId,date,startTime,endTime,available:!isPast_(date,startTime)&&!active.has(`${date}|${startTime}|${endTime}`)}}).sort((x,y)=>`${x.date} ${x.startTime}`.localeCompare(`${y.date} ${y.startTime}`))}
function getCalendarAll_(req){auth_(req,false);const active=new Set(rows_(CONFIG.SHEETS.RESERVATIONS).filter(r=>r.status==='ACTIVE').map(r=>`${normalizeDate_(r.date)}|${normalizeTime_(r.startTime)}|${normalizeTime_(r.endTime)}`));return rows_(CONFIG.SHEETS.SLOTS).filter(s=>bool_(s.enabled)&&isBookableDate_(s.date)).map(s=>{const date=normalizeDate_(s.date),startTime=normalizeTime_(s.startTime),endTime=normalizeTime_(s.endTime);return{slotId:s.slotId,date,startTime,endTime,available:!isPast_(date,startTime)&&!active.has(`${date}|${startTime}|${endTime}`)}}).sort((x,y)=>`${x.date} ${x.startTime}`.localeCompare(`${y.date} ${y.startTime}`))}
function createReservation_(req){const a=auth_(req,false),slotId=String(req.slotId||'');if(!slotId)throw new AppError('예약 시간을 선택해 주세요.');const lock=LockService.getScriptLock();try{lock.waitLock(10000)}catch(e){throw new AppError('예약 요청이 많습니다. 잠시 후 다시 시도해 주세요.')}try{const slot=rows_(CONFIG.SHEETS.SLOTS).find(s=>s.slotId===slotId);if(!slot||!bool_(slot.enabled))throw new AppError('예약할 수 없는 시간입니다.');const date=validDate_(normalizeDate_(slot.date)),start=validTime_(normalizeTime_(slot.startTime)),end=validTime_(normalizeTime_(slot.endTime));if(!isBookableDate_(date))throw new AppError('예약할 수 없는 날짜입니다.');if(start>=end)throw new AppError('예약 시간 설정이 올바르지 않습니다.');if(isPast_(date,start))throw new AppError('이미 지난 시간은 예약할 수 없습니다.');const reservations=rows_(CONFIG.SHEETS.RESERVATIONS);if(reservations.some(r=>r.status==='ACTIVE'&&r.userId===a.user.userId))throw new AppError('예약은 1인당 1개만 가능합니다. 기존 예약을 취소한 후 다시 예약해 주세요.');if(reservations.some(r=>r.status==='ACTIVE'&&normalizeDate_(r.date)===date&&normalizeTime_(r.startTime)===start&&normalizeTime_(r.endTime)===end))throw new AppError('방금 다른 사용자가 예약한 시간입니다. 다른 시간을 선택해 주세요.');const reservationId=uuid_();sheet_(CONFIG.SHEETS.RESERVATIONS).appendRow([reservationId,date,start,end,a.user.userId,a.user.company,a.user.name,a.user.departmentId,'ACTIVE',new Date()]);return{reservationId}}finally{lock.releaseLock()}}
function getMyReservations_(req){const a=auth_(req,false);return rows_(CONFIG.SHEETS.RESERVATIONS).filter(r=>r.userId===a.user.userId).map(r=>({...r,date:normalizeDate_(r.date),startTime:normalizeTime_(r.startTime),endTime:normalizeTime_(r.endTime),isPast:isPast_(normalizeDate_(r.date),normalizeTime_(r.endTime))})).sort((x,y)=>`${y.date} ${y.startTime}`.localeCompare(`${x.date} ${x.startTime}`))}
function cancelReservation_(req){const a=auth_(req,false),r=rows_(CONFIG.SHEETS.RESERVATIONS).find(x=>x.reservationId===String(req.reservationId||''));if(!r||r.userId!==a.user.userId)throw new AppError('예약 정보를 찾을 수 없습니다.');if(r.status!=='ACTIVE')throw new AppError('이미 취소된 예약입니다.');sheet_(CONFIG.SHEETS.RESERVATIONS).getRange(r._row,9).setValue('CANCELLED');return{reservationId:r.reservationId}}

function getUsers_(req){auth_(req,true);const dm=departmentMap_();return rows_(CONFIG.SHEETS.USERS).map(r=>({userId:r.userId,company:r.company,name:r.name,departmentId:r.departmentId,departmentName:dm[r.departmentId]?.departmentName||'',enabled:bool_(r.enabled)}))}
function saveUser_(req){auth_(req,true);const x=req.user||{},id=String(x.userId||uuid_()),company=requiredText_(x.company,'회사명'),name=requiredText_(x.name,'이름'),dept=String(x.departmentId||'');if(!departmentMap_()[dept])throw new AppError('존재하지 않는 부서입니다.');upsert_(CONFIG.SHEETS.USERS,'userId',id,[id,company,dept,name,!!x.enabled]);return{userId:id}}
function getDepartments_(req){auth_(req,true);return rows_(CONFIG.SHEETS.DEPARTMENTS).map(r=>({departmentId:r.departmentId,company:r.company,departmentName:r.departmentName,enabled:bool_(r.enabled)}))}
function saveDepartment_(req){auth_(req,true);const x=req.department||{},id=String(x.departmentId||uuid_()),company=requiredText_(x.company,'회사명'),name=requiredText_(x.departmentName,'부서명');upsert_(CONFIG.SHEETS.DEPARTMENTS,'departmentId',id,[id,company,name,!!x.enabled]);return{departmentId:id}}
function getAvailability_(req){auth_(req,true);const from=req.from?validDate_(req.from):'0000-01-01',to=req.to?validDate_(req.to):'9999-12-31';return rows_(CONFIG.SHEETS.SLOTS).map(r=>({...r,date:normalizeDate_(r.date),startTime:normalizeTime_(r.startTime),endTime:normalizeTime_(r.endTime),enabled:bool_(r.enabled)})).filter(r=>r.date>=from&&r.date<=to).sort((a,b)=>`${a.date} ${a.startTime}`.localeCompare(`${b.date} ${b.startTime}`))}
function saveAvailability_(req){auth_(req,true);const x=req.availability||{},date=validDate_(normalizeDate_(x.date)),start=validTime_(normalizeTime_(x.startTime)),end=validTime_(normalizeTime_(x.endTime));if(!isBookableDate_(date))throw new AppError('주말 또는 예약 불가일에는 일정을 등록할 수 없습니다.');if(start>=end)throw new AppError('종료 시간은 시작 시간보다 늦어야 합니다.');const id=x.slotId||uuid_();upsert_(CONFIG.SHEETS.SLOTS,'slotId',id,[id,date,start,end,!!x.enabled]);return{slotId:id}}
function getAllReservations_(req){auth_(req,true);const dm=departmentMap_();return rows_(CONFIG.SHEETS.RESERVATIONS).map(r=>({...r,date:normalizeDate_(r.date),startTime:normalizeTime_(r.startTime),endTime:normalizeTime_(r.endTime),departmentName:dm[r.departmentId]?.departmentName||''})).sort((a,b)=>`${b.date} ${b.startTime}`.localeCompare(`${a.date} ${a.startTime}`))}
function cancelReservationByMaster_(req){auth_(req,true);const r=rows_(CONFIG.SHEETS.RESERVATIONS).find(x=>x.reservationId===String(req.reservationId||''));if(!r)throw new AppError('예약 정보를 찾을 수 없습니다.');if(r.status!=='ACTIVE')throw new AppError('이미 취소된 예약입니다.');sheet_(CONFIG.SHEETS.RESERVATIONS).getRange(r._row,9).setValue('CANCELLED');return{reservationId:r.reservationId}}
function upsert_(sheetName,keyName,keyValue,values){const sh=sheet_(sheetName),existing=rows_(sheetName).find(r=>r[keyName]===keyValue);if(existing)sh.getRange(existing._row,1,1,values.length).setValues([values]);else sh.appendRow(values)}

/** 최초 1회 실행: 시스템 시트와 헤더를 생성합니다. */
function setupSheets(){const ss=ss_();Object.keys(HEADERS).forEach(name=>{let sh=ss.getSheetByName(name);if(!sh)sh=ss.insertSheet(name);if(sh.getLastRow()===0)sh.getRange(1,1,1,HEADERS[name].length).setValues([HEADERS[name]]);sh.setFrozenRows(1);sh.getRange(1,1,1,HEADERS[name].length).setFontWeight('bold').setBackground('#15365b').setFontColor('#ffffff');sh.autoResizeColumns(1,HEADERS[name].length)})}

/**
 * 명단.xlsx의 '사용자명단', '예약가능날짜' 시트를 같은 Spreadsheet로 가져온 뒤 1회 실행하세요.
 * Users, Departments, AvailableSlots, Reservations, Masters의 기존 내용은 초기화됩니다.
 */
function resetSystemFromImportedSheets(){
  const ss=ss_(),roster=ss.getSheetByName('사용자명단'),schedule=ss.getSheetByName('예약가능날짜');
  if(!roster||!schedule)throw new Error("'사용자명단'과 '예약가능날짜' 시트를 먼저 가져와 주세요.");
  setupSheets();
  const people=roster.getRange(2,1,Math.max(roster.getLastRow()-1,0),3).getDisplayValues().map(r=>({company:r[0].trim(),department:r[1].trim(),name:r[2].trim()})).filter(x=>x.company&&x.department&&x.name);
  if(!people.some(x=>x.company==='티에스이'&&x.name==='조다은'))people.push({company:'티에스이',department:'인사총무',name:'조다은'});
  const deptRows=[],deptIds={};
  people.forEach(x=>{const key=`${x.company}|${x.department}`;if(!deptIds[key]){deptIds[key]=uuid_();deptRows.push([deptIds[key],x.company,x.department,true])}});
  const userRows=people.map(x=>[uuid_(),x.company,deptIds[`${x.company}|${x.department}`],x.name,true]);
  const rawDates=schedule.getRange(2,1,Math.max(schedule.getLastRow()-1,0),5).getValues().flat().filter(Boolean).map(normalizeDate_).filter(x=>/^\d{4}-\d{2}-\d{2}$/.test(x));
  const dates=[...new Set(rawDates)].filter(isBookableDate_).sort();
  const timeRows=schedule.getRange(2,7,Math.max(schedule.getLastRow()-1,0),1).getDisplayValues().flat().map(String).map(x=>x.match(/(\d{1,2}:\d{2})\s*[~～-]\s*(\d{1,2}:\d{2})/)).filter(Boolean).map(m=>[normalizeTime_(m[1]),normalizeTime_(m[2])]);
  const slotRows=[];dates.forEach(date=>timeRows.forEach(([start,end])=>slotRows.push([uuid_(),date,start,end,true])));
  const data={Departments:deptRows,Users:userRows,AvailableSlots:slotRows,Reservations:[],Masters:[['티에스이','인사총무','조다은',true]]};
  Object.keys(data).forEach(name=>{const sh=sheet_(name),headers=HEADERS[name];sh.clearContents();sh.getRange(1,1,1,headers.length).setValues([headers]);if(data[name].length)sh.getRange(2,1,data[name].length,headers.length).setValues(data[name]);sh.setFrozenRows(1);sh.getRange(1,1,1,headers.length).setFontWeight('bold').setBackground('#15365b').setFontColor('#ffffff');sh.autoResizeColumns(1,headers.length)});
  return{users:userRows.length,departments:deptRows.length,dates:dates.length,slots:slotRows.length};
}
